general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
      deployTool: 'mtaDeployPlugin'
      deployType: 'standard'
      cloudFoundry:
        org: '456951f2trial'
        space: 'dev'
        credentialsId: 'CF_CREDENTIALSID'
