general:
steps:
  mtaBuild:
    buildTarget: 'CF'
  cloudFoundryDeploy:
      deployTool: 'mtaDeployPlugin'
      deployType: 'standard'
      cloudFoundry:
        org: '456951f2trial'
        space: 'dev'
        credentialsId: '0d7898e6-0b68-47a0-a7ab-a19a64a5ed04'
